cswrap: black list config-temp/qemu-conf.c
Otherwise qemu-guest-agent-2.12.0-1.el7 fails to build:

Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.sYNrK4
+ umask 022
+ cd /builddir/build/BUILD
+ cd qemu-2.12.0
+ buildarch=x86_64-softmmu
+ extraldflags=-Wl,--build-id
+ buildldflags=VL_LDFLAGS=-Wl,--build-id
+ cp /builddir/build/SOURCES/build_configure.sh build_configure.sh
+ ./build_configure.sh /usr /usr/lib64 /etc /var /usr/libexec qemu-ga x86_64 qemu-guest-agent-2.12.0-1.el7 '-O2 -g -pipe -Wall  -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic' disable enable --target-list= --cpu=x86_64
./configure: --disable-vhdx is obsolete, VHDX driver is always built

ERROR: Your compiler does not support the __thread specifier for
       Thread-Local Storage (TLS). Please upgrade to a version that does.